# Generated by Django 4.0.3 on 2022-05-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Descarga', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Discipulado',
                'verbose_name_plural': 'Discipulados',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('descarga', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
